### ISSUE TITLE
Timeline in mobile

### ISSUE THREAD

**Issue by vorvek** [DylanHalstead/PolyChord-Website#3]
Making the timeline in the About Us section responsive is not straightforward and a decision needs to be made. We can either make it link to a full size version the user can navigate through, or we have to encase it in some sort of scrollable container.

![image](https://user-images.githubusercontent.com/9655848/187940654-0c9b9e9a-df8c-4c52-8ebb-f104b2543bf8.png)

Obviously, the link is much simpler and may work as a quick solution, but the result is somewhat cheap. We can add some text that only appears at resolutions < 768px that says "click to see full timeline" and open the link in another tab, or even in another custom made page. Another option would be to integrate a simple lightbox that already comes with some zooming options, there's probably a few of these, ready-made.

Let me know your thoughts.

**Comment by DylanHalstead** [comment]
The idea was this image would be replaced with some plug-in that would allow the text to be enlarged whenever hovered and when in a mobile environment, let the user scroll the time-line left and right. I think the lightbox option would be a more eloquent fix than the link for sure. Let me do some research into some options and I'll get back to you

**Comment by DylanHalstead** [comment]
Here's an ok solution: https://codepen.io/alvarotrigo/pen/BawBzjM

We could create something in this vein for mobile and for desktop we can make its display: none.

The horizontal layout of the img isn't very mobile friendly so having something completely different and verticle seems like the way.

If you agree with this I can make something real quick for this and push it to main

**Comment by vorvek** [comment]
Sure, it looks quite cool.

**Comment by DylanHalstead** [comment]
I've created a version of the above timeline, closing issue for now
