### ISSUE TITLE
MIDAS Illistrations Compatability issues

### ISSUE THREAD

**Issue by DylanHalstead** [DylanHalstead/PolyChord-Website#5]
If you use anything with a chromium base, as of now the MIDAS Illustrations look like complete nonsense, however, on Firefox it works without any issues. I'm not sure if it's an issue specifically with the p5.js library I'm using or an issue with Chrome being restricting with how the DOM is directly changed.

I could just take a video of the animations, being that they already loop, and use those (is most likely also less resource intensive). The issue with that is the way I have the "with/without" MIDAS section, I worry that if I turn that into a video getting the typewriter effect to match up with the looping video will be an issue (the way it's setup right now is it waits till the text changes rather than being set to a timer).

Any thoughts on how to circumvent this issue? It seems just taking the working animations and turning them into mp4's is the easiest/best solution, but I'd like to hear if you think there's a better way

**Comment by vorvek** [comment]
Ah, I was wondering what that was. We could potentially add the text to the video, although it won't look great. Maybe an animated WebP will do the trick. Obviously we cannot drop Webkit support for the site, as that's probably 90% of possible users. I'll look into it once we are done with the styling.

Also, the typewriter javascript could potentially be adjusted by checking the load event of a WebP image. We can also choose not to display it until it's completely loaded.

**Comment by DylanHalstead** [comment]
Vis has been turned into videos. They seem to work and line up well enough, they need to be cropped a bit to remove black edge, will fix tmrw. Closing issue for now
