### ISSUE TITLE
Polytrack

### ISSUE THREAD

**Issue by vorvek** [DylanHalstead/PolyChord-Website#7]
Is there any reason why the sensors on the train are different images? Are they supposed to move in any way? Because otherwise, they should be part of the image, or making them responsive will be pretty much hell.

**Comment by DylanHalstead** [comment]
The idea was to have the sensors flash (0 transparency to 100) while the train moves back and forth (to give the illusion of a moving train)

This idea can be scratched if it's a bit difficult to have this working in a mobile-friendly environment. The static image gets the point across fairly well in my opinion.

I can export a version of the train with the dots:
![sensors](https://user-images.githubusercontent.com/70990184/188781171-69d40d3a-5188-4d78-a0a9-faf2cc07fb10.png)
